Repository GDSC-SWU/2024-ProDiction-SolutionChallenge, pull requests merged in 2024-02, with the labels that each got.

#11 feat #10: GCP를 이용한 배포
  Server/Dockerfile
Labels: deployment

#15 feat #12: 발음 테스트 API
  Server/src/main/java/com/pro_diction/server/ServerApplication.java
  Server/src/main/java/com/pro_diction/server/domain/model/Stage.java
  Server/src/main/java/com/pro_diction/server/domain/study/entity/Study.java
  Server/src/main/java/com/pro_diction/server/domain/study/exception/StudyNotFoundException.java
  Server/src/main/java/com/pro_diction/server/domain/study/repository/StudyRepository.java
  Server/src/main/java/com/pro_diction/server/domain/test/controller/TestController.java
  Server/src/main/java/com/pro_diction/server/domain/test/dto/TestApiResponseDto.java
  Server/src/main/java/com/pro_diction/server/domain/test/dto/TestApiResponseObjectDto.java
  Server/src/main/java/com/pro_diction/server/domain/test/dto/TestContentResponseDto.java
  Server/src/main/java/com/pro_diction/server/domain/test/dto/TestResponseDto.java
  Server/src/main/java/com/pro_diction/server/domain/test/entity/Test.java
  Server/src/main/java/com/pro_diction/server/domain/test/exception/InvalidStageException.java
  Server/src/main/java/com/pro_diction/server/domain/test/repository/TestRepository.java
  Server/src/main/java/com/pro_diction/server/domain/test/service/TestService.java
  Server/src/main/java/com/pro_diction/server/domain/test/service/TestServiceImpl.java
  Server/src/main/java/com/pro_diction/server/global/constant/ErrorCode.java
  Server/src/main/resources/application.yml
Labels: feature, fix

#16 feat #5: 기능 개발을 위해 필요한 필드 추가
  Server/src/main/java/com/pro_diction/server/domain/study/entity/Study.java
Labels: feature

#28 feat #24: 단어장 API
  Server/src/main/java/com/pro_diction/server/domain/member/exception/MemberNotFoundException.java
  Server/src/main/java/com/pro_diction/server/domain/vocabulary/controller/VocabularyController.java
  Server/src/main/java/com/pro_diction/server/domain/vocabulary/dto/SaveVocabularyResponseDto.java
  Server/src/main/java/com/pro_diction/server/domain/vocabulary/dto/VocabularyResponseDto.java
  Server/src/main/java/com/pro_diction/server/domain/vocabulary/entity/Vocabulary.java
  Server/src/main/java/com/pro_diction/server/domain/vocabulary/exception/DuplicatedVocabularyException.java
  Server/src/main/java/com/pro_diction/server/domain/vocabulary/exception/VocabularyNotFoundException.java
  Server/src/main/java/com/pro_diction/server/domain/vocabulary/repository/VocabularyRepository.java
  Server/src/main/java/com/pro_diction/server/domain/vocabulary/service/VocabularyService.java
  Server/src/main/java/com/pro_diction/server/domain/vocabulary/service/VocabularyServiceImpl.java
  Server/src/main/java/com/pro_diction/server/global/constant/ErrorCode.java
Labels: feature

#31 refactor #17: StudyService 리팩토링
  Server/src/main/java/com/pro_diction/server/domain/study/controller/StudyController.java
  Server/src/main/java/com/pro_diction/server/domain/study/dto/StudyRequestDto.java
  Server/src/main/java/com/pro_diction/server/domain/study/dto/StudyResponseDto.java
  Server/src/main/java/com/pro_diction/server/domain/study/dto/StudyResultDto.java
  Server/src/main/java/com/pro_diction/server/domain/study/dto/SubCategoryRequestDto.java
  Server/src/main/java/com/pro_diction/server/domain/study/service/StudyService.java
  Server/src/main/java/com/pro_diction/server/domain/study/service/StudyServiceImpl.java
Labels: feature, refactor

#32 refactor #2: Member 코드 정리, 오류 응답 형식 통일
  Server/src/main/java/com/pro_diction/server/domain/member/controller/MemberController.java
  Server/src/main/java/com/pro_diction/server/domain/member/exception/IdTokenRequiredException.java
  Server/src/main/java/com/pro_diction/server/domain/member/service/MemberServiceImpl.java
  Server/src/main/java/com/pro_diction/server/global/exception/auth/AccessTokenRequiredException.java
  Server/src/main/java/com/pro_diction/server/global/exception/auth/InvalidIdTokenException.java
  Server/src/main/java/com/pro_diction/server/global/exception/auth/InvalidTokenException.java
  Server/src/main/java/com/pro_diction/server/global/exception/auth/RefreshTokenRequiredException.java
  Server/src/main/java/com/pro_diction/server/global/util/GoogleOAuthUtil.java
  Server/src/main/java/com/pro_diction/server/global/util/JwtUtil.java
Labels: feature, refactor

#33 fix #2: 기존 유저가 새로운 유저로 저장되었던 오류 수정
  Server/src/main/java/com/pro_diction/server/domain/member/service/MemberServiceImpl.java
Labels: fix

#34 feat #30: 마이페이지 API
  Server/src/main/java/com/pro_diction/server/domain/member/controller/MemberController.java
  Server/src/main/java/com/pro_diction/server/domain/member/dto/MemberResponseDto.java
  Server/src/main/java/com/pro_diction/server/domain/member/service/MemberService.java
  Server/src/main/java/com/pro_diction/server/domain/member/service/MemberServiceImpl.java
  Server/src/main/java/com/pro_diction/server/domain/model/Stage.java
Labels: feature

#36 feat #35: 학습 기능 수정
  Server/src/main/java/com/pro_diction/server/domain/study/controller/StudyController.java
  Server/src/main/java/com/pro_diction/server/domain/study/dto/DetailStudyResponseDto.java
  Server/src/main/java/com/pro_diction/server/domain/study/dto/StudyResultDto.java
  Server/src/main/java/com/pro_diction/server/domain/study/service/StudyService.java
  Server/src/main/java/com/pro_diction/server/domain/study/service/StudyServiceImpl.java
  Server/src/main/java/com/pro_diction/server/domain/test/controller/TestController.java
  Server/src/main/java/com/pro_diction/server/domain/test/dto/TestResponseDto.java
  Server/src/main/java/com/pro_diction/server/domain/test/service/TestService.java
  Server/src/main/java/com/pro_diction/server/domain/test/service/TestServiceImpl.java
  Server/src/main/java/com/pro_diction/server/global/util/DictionTestUtil.java
Labels: feature

#40 feat #29: 학습 검색 API
  Server/src/main/java/com/pro_diction/server/ServerApplication.java
  Server/src/main/java/com/pro_diction/server/domain/search/controller/SearchController.java
  Server/src/main/java/com/pro_diction/server/domain/search/dto/SearchContentHistoryDto.java
  Server/src/main/java/com/pro_diction/server/domain/search/dto/SearchResponseDto.java
  Server/src/main/java/com/pro_diction/server/domain/search/entity/Search.java
  Server/src/main/java/com/pro_diction/server/domain/search/exception/KeywordRequiredException.java
  Server/src/main/java/com/pro_diction/server/domain/search/exception/SearchNotFoundException.java
  Server/src/main/java/com/pro_diction/server/domain/search/repository/SearchRepository.java
  Server/src/main/java/com/pro_diction/server/domain/search/service/SearchService.java
  Server/src/main/java/com/pro_diction/server/domain/search/service/SearchServiceImpl.java
  Server/src/main/java/com/pro_diction/server/domain/study/repository/StudyRepository.java
  Server/src/main/java/com/pro_diction/server/global/constant/ErrorCode.java
  Server/src/test/java/com/pro_diction/server/domain/search/service/SearchServiceTest.java
Labels: feature, test

#44 feat #18: Develop FastAPIs
  AI/README.md
  AI/develop fastapi/main.py
  AI/develop fastapi/test_main.http
Labels: feature

#46 feat#5: Modify member in Test entity from ManyToOne to OneToOne
  Server/src/main/java/com/pro_diction/server/domain/member/entity/Member.java
  Server/src/main/java/com/pro_diction/server/domain/member/service/MemberServiceImpl.java
  Server/src/main/java/com/pro_diction/server/domain/test/entity/Test.java
Labels: feature

#50 feat #29: Add Transactional to unnecessary search delete API
  Server/src/main/java/com/pro_diction/server/domain/search/service/SearchServiceImpl.java
Labels: feature
